# Generated by Django 2.2.7 on 2019-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20191118_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='sexo',
        ),
        migrations.AddField(
            model_name='clientes',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Disponible'), ('f', 'Fuera de servicio'), ('v', 'Vendido')], default='d', help_text='Genero', max_length=1),
        ),
    ]
