# Generated by Django 2.2.7 on 2019-11-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20191118_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='status',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('-', 'No especificado')], default='-', help_text='Genero', max_length=1),
        ),
    ]
