# Generated by Django 2.2.7 on 2019-11-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20191118_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
