# Generated by Django 2.2.7 on 2019-11-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20191118_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desarrolladora',
            options={'verbose_name': 'Desarrolladora', 'verbose_name_plural': 'Desarrolladoras'},
        ),
        migrations.AlterModelOptions(
            name='juegos',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
    ]
