# Generated by Django 2.2.7 on 2019-11-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20191118_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['nombre_cliente'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
