# Generated by Django 2.2.7 on 2019-11-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20191118_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desarrolladora',
            options={'ordering': ['nombre_desarrolladora'], 'verbose_name': 'Desarrolladora', 'verbose_name_plural': 'Desarrolladoras'},
        ),
        migrations.AlterModelOptions(
            name='juegos',
            options={'ordering': ['nombreJuego'], 'verbose_name': 'Juego', 'verbose_name_plural': 'Juegos'},
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='status',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=120, verbose_name='TU DIRECCION'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='TU CORREO ELECTRONICO:'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre_cliente',
            field=models.CharField(max_length=120, verbose_name='TU NOMBRE '),
        ),
        migrations.AlterField(
            model_name='desarrolladora',
            name='nombre_desarrolladora',
            field=models.CharField(max_length=120, verbose_name='Nombre de la desarrolladora: '),
        ),
        migrations.AlterField(
            model_name='generojuego',
            name='nombre_genero',
            field=models.CharField(max_length=120, verbose_name='Genero del juego: '),
        ),
    ]
