# Generated by Django 2.2.7 on 2019-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20191119_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('-', 'No especificado')], default='-', help_text='genero', max_length=1),
        ),
    ]
